# Generated by Django 2.1.8 on 2019-04-23 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('end_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lovers',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
