# Generated by Django 2.1.7 on 2019-04-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
